defaults: &defaults
  sessions:
    default:
      options:
        consistency: :strong
        max_retries: 5
  options:
    allow_dynamic_fields: false
    use_utc: true

development:
  <<: *defaults
  sessions:
    default:
      database: responsive_development
      hosts:
        - localhost:27017
      options:
        consistency: :strong
